"""initial agent schema

Revision ID: 63d589f0b8df
Revises:
Create Date: 2026-07-22 09:27:59.732471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63d589f0b8df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions')),
    schema='agent'
    )
    op.create_table('episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', summary)", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    schema='agent'
    )
    op.create_index('ix_episodes_summary_tsv', 'episodes', ['summary_tsv'], unique=False, schema='agent', postgresql_using='gin')
    op.create_table('facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', subject || ' ' || content)", persisted=True), nullable=False),
    sa.CheckConstraint("source IN ('user', 'consolidation')", name=op.f('ck_facts_source_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts')),
    schema='agent'
    )
    op.create_index('ix_facts_content_tsv', 'facts', ['content_tsv'], unique=False, schema='agent', postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consolidated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['agent.chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    schema='agent'
    )
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False, schema='agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages', schema='agent')
    op.drop_table('chat_messages', schema='agent')
    op.drop_index('ix_facts_content_tsv', table_name='facts', schema='agent', postgresql_using='gin')
    op.drop_table('facts', schema='agent')
    op.drop_index('ix_episodes_summary_tsv', table_name='episodes', schema='agent', postgresql_using='gin')
    op.drop_table('episodes', schema='agent')
    op.drop_table('chat_sessions', schema='agent')
    # ### end Alembic commands ###
