"""chat_messages insertion-order sequence

Revision ID: 899d3cd20b50
Revises: 63d589f0b8df
Create Date: 2026-07-22 11:24:54.841946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899d3cd20b50'
down_revision: Union[str, Sequence[str], None] = '63d589f0b8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False), schema='agent')
    op.drop_index(op.f('ix_chat_messages_session_created'), table_name='chat_messages', schema='agent')
    op.create_index('ix_chat_messages_session_seq', 'chat_messages', ['session_id', 'seq'], unique=False, schema='agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_session_seq', table_name='chat_messages', schema='agent')
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False, schema='agent')
    op.drop_column('chat_messages', 'seq', schema='agent')
    # ### end Alembic commands ###
